Реализована генерация раундовых ключей
SergeyBrian/rsa_gpu pull request #5
Opened 2023-11-28 06:33 UTC by iamlukadaniel

2023-11-28 16:27 UTC, SergeyBrian requested changes

2023-11-28 16:27 UTC, SergeyBrian commented on app/core/encryption/AES/gpu/aesgpu_backend.cpp
> +/*    RCon = cl::Buffer(context, CL_MEM_READ_ONLY, sizeof(encryption::aes::RCon));*/
Лучше полностью удалить

2023-11-28 16:27 UTC, SergeyBrian commented on app/core/encryption/AES/gpu/aesgpu_backend.cpp
> +/*    command_queue.enqueueWriteBuffer(RCon,
Лучше полностью удалить

2023-11-28 16:27 UTC, SergeyBrian commented on app/core/encryption/math_utils.hpp
> +using word = unsigned int;
А этот тип где-то используется вообще? Мб его лучше полностью убрать

2023-11-29 04:55 UTC, iamlukadaniel commented on app/core/encryption/math_utils.hpp
> +using word = unsigned int;
Несколько строк в расширении ключа есть, пусть останется

2023-11-29 13:38 UTC, SergeyBrian approved these changes

2023-11-29 13:38 UTC, merged